import Head from "next/head";
import { Inter } from "@next/font/google";
import Layout from "../src/Layout/Layout";
import LandingPage from "./LandingPage";
// import Footer from "../src/Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>DeCarbonUs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <LandingPage key="home" />
      </Layout>
      <style jsx global>{`
  html,
  body {
    padding: 0;
    margin: 0;
    font-family: Andika;
  }

  * {
    box-sizing: border-box;
  }
`}</style>
    </>
  );
}
